apiVersion: 1.0
kind: terraform
builds:
- name: service-a
  image: node
  commands:
  - npm install
apply:
  module: deployment
  variables:
    resource_group: $(resourceGroup)
    default_location: $(location)
push:
- type: app-service-zip-deploy
  ignore:
  - azds.yaml
  resource: service_a
